var refEn = {"site-map": {
	"ABOUT": "Babykarte helps parents of infants and toddlers to search for changing tables, playgrounds etc. It also shows the baby friendliness of cafes and restaurants.",
	"USAGE": "Icons in the details view for POI's:",
	"MENUBUTTONS": {
		"btn_info": "Show help",
		"btn_lang": "Select language",
		"btn_search": "Search for a place",
		"btn_filtersbar": "Select POI's to show",
		"btn_locating": "Shows your location"
	},
	"MAP_MARKERDOTS_GENERAL": "Traffic light system for indication of baby friendliness of restaurants und cafes:",
	"MAP_MARKERDOTS": {
		"rating-green": "This place is baby friendly",
		"rating-yellow": "Baby friendliness is limited",
		"rating-red": "This place isn't baby friendly",
	},
	"PDV_ICONS_EXPLANATION_GENERAL": "The Icons shown in grey here are colored according to the traffic light system described above.",
	"PDV_ICONS_EXPLANATION": {
		"PDV_ICON_CHANGINGTABLE": "<img class='small-icon' src='images/changingtable.svg' /> Changing table",
		"PDV_ICON_HIGHCHAIR": "<img class='small-icon' src='images/highchair.svg' /> Highchairs",
		"PDV_ICON_STROLLER": "<img class='small-icon' src='images/stroller.svg' /> Suitability for strollers",
		"PDV_ICON_BALL": "<img class='small-icon' src='images/ball.svg' /> Kids area",
		"PDV_ICON_BREASTFEEDING": "<span class='small-icon'>&#129329;</span> Feeding facilities <br>",
		"PDV_ICON_PEN": "<span class='small-icon'>✏️</span> Edit in OpenStreetMap (external website, registration necessary)",
		"PDV_ICON_SHARE": "<img class='small-icon' src='images/share.svg' /> Share POI"
	},
	"LOCATING_FAILURE": "Did not find your location",
	"LOCATING_SUCCESS": "Your location",
	"LOADING_FAILURE": "An error occurred, zoom in and try again please",
	"NODATA": "No '<i>%s</i>' found here!",
	"ERROR404": "Backend does not support filter '<i>%s</i>'",
	"ERROR503": "Error in requesting database for filter '<i>%s</i>'",
	"ERROR": "An unknown error interrupts the party",
	"AGE_RANGE": "👶 %1 - %2",
	"LNK_OSM_EDIT": "Edit in OSM",
	"LNK_OSM_REPORT": "Report wrong information",
	"LNK_OSM_VIEW": "View POI in OpenStreetMap",
	"LNK_OPEN_WITH": "Open with an app",
	"FLTR_NOTHINGSELECTED": "Please touch the <img class='bar-icon' src='images/checkmark.svg' /> icon in the menu to select filters or the <img class='bar-icon' src='images/info.svg.png' /> one to get help using Babykarte.",
	"FLTR_SELECTALL": "(De)select all",
	"PDV_UNNAME": "No Name",
	"PDV_CONTACT_WEBSITE_*": "%s",
	"PDV_CONTACT_EMAIL_*": "%s",
	"PDV_CONTACT_FACEBOOK_*": "%s",
	"PDV_CONTACT_PHONE_*": "%s",
	"PDV_WEBSITE_*": "%s",
	"PDV_EMAIL_*": "%s",
	"PDV_FACEBOOK_*": "%s",
	"PDV_PHONE_*": "%s",
	"PDV_ZIPCODE_UNKNOWN": "Zipcode not known",
	"PDV_STREET_UNKNOWN": "Street unknown",
	"PDV_ADDRESS_UNKNOWN": "Address unknown",
	"PDV_ADDRESS_LOADING": "<i class='color-red'>Address loading</i>",
	"PDV_HOUSENUMBER_UNKNOWN": "?",
	"PDV_COMMUNE_UNKNOWN": "?",
	"PDV_TITLE_HOME": "General",
	"PDV_TITLE_BABY": "Baby friendliness",
	"PDV_TITLE_OH": "Opening hours",
	"PDV_TITLE_CONTACT": "Contact",
	"PDV_TITLE_MI": "More information",
	"PDV_DIAPER_YES": "Changing table",
	"PDV_DIAPER_*": "Changing table",
	"PDV_DIAPER_LIMITED": "Limited changing facilities",
	"PDV_DIAPER_ROOM": "Diaper-changing room",
	"PDV_DIAPER_MALE_YES": "male toilet",
	"PDV_DIAPER_FEMALE_YES": "female toilet",
	"PDV_DIAPER_UNISEX_YES": "unisex toilet",
	"PDV_DIAPER_FEE_YES": "Fee applies",
	"PDV_DIAPER_FEE_NO": "No fees",
	"PDV_CHANGINGTABLE_YES": "Changing table",
	"PDV_CHANGINGTABLE_LIMITED": "limited changing facilities",
	"PDV_CHANGINGTABLE_LOCATION_ROOM": "Multi-purpose room",
	"PDV_CHANGINGTABLE_LOCATION_DEDICATEDROOM": "Diaper-changing room",
	"PDV_CHANGINGTABLE_LOCATION_MALETOILET": "male toilet",
	"PDV_CHANGINGTABLE_LOCATION_FEMALETOILET": "female toilet",
	"PDV_CHANGINGTABLE_LOCATION_UNISEXTOILET": "unisex toilet",
	"PDV_CHANGINGTABLE_LOCATION_WHEELCHAIRTOILET": "wheelchair users' toilet",
	"PDV_CHANGINGTABLE_LOCATION_SALESAREA": "Sales area",
	"PDV_CHANGINGTABLE_FEE_YES": "fee applies",
	"PDV_CHANGINGTABLE_FEE_NO": "no fees",
	"PDV_HIGHCHAIR_YES": "Highchair",
	"PDV_HIGHCHAIR_*": "Highchairs",
	"PDV_KIDSAREA_YES": "Kids area",
	"PDV_KIDSAREA_INDOOR_YES": "Inside",
	"PDV_KIDSAREA_OUTDOOR_YES": "Outside",
	"PDV_KIDSAREA_SUPERVISED_YES": "Supervised",
	"PDV_KIDSAREA_FEE_YES": "Fee applies",
	"PDV_STROLLER_YES": "Stroller friendly",
	"PDV_STROLLER_LIMITED": "Partially stroller friendly",
	"PDV_STROLLER_NO": "Not stroller friendly",
	"PDV_BABYFEEDING_YES": "(Breast-)feeding",
	"PDV_BABYFEEDING_NO": "No (breast-)feeding",
	"PDV_BABYFEEDING_ROOM": "Room",
	"PDV_BABYFEEDING_MALE_YES": "for men",
	"PDV_BABYFEEDING_FEMALE_YES": "For women",
	"PDV_LEISURE_PLAYGROUND": "Playground equipment",
	"PDV_MINAGE_*": "Min age: %s",
	"PDV_MAXAGE_*": "Max age: %s",
	"PDV_PLAYGROUND_SLIDE_YES": "Slide",
	"PDV_PLAYGROUND_SWING_YES": "Swing",
	"PDV_PLAYGROUND_CLIMBINGFRAME_YES": "Climbing frame",
	"PDV_PLAYGROUND_CLIMBINGWALL_YES": "Climbing wall",
	"PDV_PLAYGROUND_SLEDDING_YES": "Sledding",
	"PDV_PLAYGROUND_SANDPIT_YES": "Sandpit",
	"PDV_PLAYGROUND_SEESAW_YES": "Seesaw",
	"PDV_PLAYGROUND_SPRINGY_YES": "Springy",
	"PDV_PLAYGROUND_PLAYHOUSE_YES": "Playhouse",
	"PDV_PLAYGROUND_ROUNDABOUT_YES": "Roundabout",
	"PDV_PLAYGROUND_MULTIPLAY_YES": "Multi play",
	"PDV_PLAYGROUND_BASKETSWING_YES": "Basket swing",
	"PDV_PLAYGROUND_STRUCTURE_YES": "Structure",
	"PDV_PLAYGROUND_ZIPWIRE_YES": "Zipwire",
	"PDV_PLAYGROUND_BALANCEBEAM_YES": "Balance beam",
	"PDV_PLAYGROUND_WATER_YES": "Water play",
	"PDV_PLAYGROUND_TRAMPOLINE_YES": "Trampoline",
	"PDV_PLAYGROUND_TEENSHELTER_YES": "Teen shelter",
	"PDV_PLAYGROUND_CHAINLADDER_YES": "Chain ladder",
	"PDV_PLAYGROUND_HOPSCOTCH_YES": "Hopscotch",
	"PDV_PLAYGROUND_CLIMBWALL_YES": "Climb wall",
	"PDV_PLAYGROUND_TUNNELTUBE_YES": "Tunnel tube",
	"PDV_PLAYGROUND_CHESSTABLE_YES": "Chess table",
	"PDV_PLAYGROUND_TREEHOUSE_YES": "Tree house",
	"PDV_PLAYGROUND_BASKETBALLBACKBOARDS_YES": "Basketball backboards",
	"PDV_PLAYGROUND_CUSHION_YES": "Cushion",
	"PDV_PLAYGROUND_SKATEEQUIPMENT_YES": "Skate equipment",
	"PDV_WHEELCHAIR_YES": "Accessible by wheelchair",
	"PDV_WHEELCHAIR_NO": "Not accessible by wheelchair",
	"PDV_MATERIAL_WOOD": "Material: wood",
	"PDV_MATERIAL_METAL": "Material: metal",
	"PDV_MATERIAL_STEEL": "Material: steel",
	"PDV_MATERIAL_PLASTIC": "Material: plastic",
	"PDV_MATERIAL_ROPE": "Material: ropes",
	"PDV_CAPACITY_DISABLED_YES": "Accessible for the disabled.",
	"PDV_CAPACITY_DISABLED_NO": "Not accessible for the disabled.",
	"PDV_BABY_YES": "Suitable for babies.",
	"PDV_BABY_NO": "Not suitable for babies.",
	"PDV_BABY_ONLY": "For babies only.",
	"PDV_SURFACE_SAND": "Surface: sand",
	"PDV_SURFACE_WOOD": "Surface: wood",
	"PDV_SURFACE_GRASS": "Surface: grass",
	"PDV_SURFACE_WOODCHIPS": "Surface: woodchips",
	"PDV_SURFACE_TARTAN": "Surface: tartan",
	"PDV_SURFACE_GRAVEL": "Surface: gravel",
	"PDV_SURFACE_PAVINGSTONES": "Surface: pavingstones",
	"PDV_SURFACE_ASPHALT": "Surface: asphalt",
	"PDV_ACCESS_YES": "Allowed use",
	"PDV_ACCESS_NO": "Forbidden use",
	"PDV_ACCESS_CUSTOMERS": "Customers only",
	"PDV_ACCESS_PRIVATE": "Private equipment",
	"PDV_OPERATOR": "Operator",
	"PDV_DESCRIPTION": "Description",
	"TOILET": "Toilet",
	"LNK_IMPRESS": "About",
	"LNK_IMPRESS_URL": "impressum.html#en",
	"LNK_PP_SITE": "Privacy (v.3)",
	"LNK_PP_SITE_URL": "privacypolicy-en.html",
	"LNK_GITHUB": "On Github",
	"LNK_OSMWIKI": "OSM Wiki",
	"TB_SEARCHFIELD": "Search",
	"opening_hours": {"Mo" : "Monday", "Tu" : "Tuesday", "We" : "Wednesday", "Th" : "Thursday", "Fr" : "Friday", "Sa" : "Saturday", "Su" : "Sunday", "off" : "closed", "Jan" : "January", "Feb" : "February", "Mar" : "March", "Apr" : "April", "May" : "May", "Jun" : "June", "Jul" : "July", "Aug" : "August", "Sep" : "September", "Oct" : "October", "Nov" : "November", "Dec" : "December", "PH" : "holiday"},
	"filtername": {
		"paediatrics": "Paediatricians / children's wards",
		"midwife": "Midwifes",
		"birthing_center": "Birthing centers",
		"playground": "Playgrounds",
		"play-equipment": "Playground equipment",
		"park": "Parks",
		"shop-babygoods": "Shops for baby goods",
		"shop-toys": "Toy shops",
		"shop-clothes": "Shops for clothes",
		"childcare": "Kindergartens and child care",
		"zoo": "Zoos",
		"changingtable": "Changing tables",
		"changingtable-men": "Only changing tables accessible for men",
		"cafe": "Cafés",
		"restaurant": "Restaurants",
		"fast_food": "Fast Food"
	}
},
"site-impress" : {
	"IMPRESS_TITLE": "About",
	"IMPRESS_SUBTITLE": "Responsible for this website",
	"IMPRESS_COUNTRY": "Germany",
	"IMPRESS_CONTACT": "Contact",
	"IMPRESS_NOTE": "All data available on this website is coming from OpenStreetMap. Babykarte just uses the data. We do not guarantee for the correctness of it. Through the provided links you can convey annotations to wrong or missing data to OpenStreetMap. You can also correct wrong ones or add further information by yourself."
	}
};
refEn["site-map"].filtertranslations = {
	"healthcare=doctor": "Pediatrician",
	"healthcare=hospital": "Hospital",
	"healthcare=midwife": "Midwife",
	"healthcare=birthing_center": "Birthing center",
	"amenity=toilets": "Toilets",
	"amenity=cafe": "Cafe",
	"amenity=restaurant": "Restaurant",
	"amenity=fast_food": "Fast food",
	"amenity=kindergarten" : "Kindergarten",
	"amenity=childcare" : "Kindergarten",
	"leisure=playground": "Playground",
	"leisure=park": "Park",
	"tourism=zoo": "Zoo",
	"shop=baby_goods": "Baby goods",
	"shop=toys": "Toy store",
	"shop=clothes": "Clothes",
	"shop=chemist": "Chemist",
	"shop=supermarket": "Supermarket"
}
registerLang("en", refEn);
setLang("", "en");
