var refFr = {
	"site-map": {
		"ABOUT": "Babykarte aide les parents de nourrissons et de tout-petits à chercher des tables à langer, des aires de jeux, etc. Il montre également l'adaptation des cafés et des restaurants aux bébés.",
		"USAGE": "Icônes dans la vue détaillée des Points d'Intérêt :",
		"MENUBUTTONS": {
			"btn_info": "Montrer l'aide",
			"btn_lang": "Choisir la langue",
			"btn_search": "Chercher un lieu",
			"btn_filtersbar": "Sélectionner un Point d'Intérêt à montrer",
			"btn_locating": "Montrer votre géolocalisation"
		},
		"MAP_MARKERDOTS_GENERAL": "Système de feux de signalisation pour l'affichage de l'adaptation aux bébés des restaurants et cafés :",
		"MAP_MARKERDOTS": {
			"rating-green": "Ce lieu est adapté aux bébés",
			"rating-yellow": "Ce lieu est partiellement adapté aux bébés. ",
			"rating-red": "Ce lieu n'est pas adapté aux bébés. ",
		},
		"PDV_ICONS_EXPLANATION_GENERAL": "Les icônes ici en gris sont coloriées selon un système de feu tricolore décrit ci-dessus",
		"PDV_ICONS_EXPLANATION": {
			"PDV_ICON_CHANGINGTABLE": "<img class='small-icon' src='images/changingtable.svg' /> Table à langer",
			"PDV_ICON_HIGHCHAIR": "<img class='small-icon' src='images/highchair.svg' /> Chaises hautes",
			"PDV_ICON_STROLLER": "<img class='small-icon' src='images/stroller.svg' /> Adaptabilité aux poussettes",
			"PDV_ICON_BALL": "<img class='small-icon' src='images/ball.svg' /> Espace enfant",
			"PDV_ICON_BREASTFEEDING": "<span class='small-icon'>&#129329;</span> Équipements d'alimentation",
			"PDV_ICON_PEN": "<span class='small-icon'>✏️</span> Modifier dans OpenStreetMap (site Web externe, inscription nécessaire)",
			"PDV_ICON_SHARE": "<img class='small-icon' src='images/share.svg' /> Partager Point d'Intérêt"
		},
		"LOCATING_FAILURE": "N'a pas trouvé votre lieu",
		"LOCATING_SUCCESS": "Votre lieu",
		"LOADING_FAILURE": "Une erreur s'est produite, veuillez zoomer et réessayer",
		"NODATA": "Aucun '<i>%s</i>' trouvé ici !",
		"ERROR404": "Le backend ne supporte pas le filtre '<i>%s</i>'",
		"ERROR503": "Erreur en requêtant la base de données avec le filtre '<i>%s</i>'",
		"ERROR": "Une erreur inconnue interrompt la fête",
		"AGE_RANGE": "👶 %1 - %2",
		"LNK_OSM_EDIT": "Modifier dans OSM",
		"LNK_OSM_REPORT": "Signaler une information erronée",
		"LNK_OSM_VIEW": "Voir le Point d'intérêt dans OpenStreetMap",
		"LNK_OPEN_WITH": "Ouvrir avec une appli",
		"FLTR_NOTHINGSELECTED": "Veuillez toucher l'icône <img class='bar-icon' src='images/checkmark.svg' /> dans le menu pour sélectionner les filtres ou cet icône <img class='bar-icon' src='images/info.svg.png' /> pour obtenir de l'aide sur Babykarte.",
		"FLTR_SELECTALL": "(De)sélectionnez tout",
		"PDV_UNNAME": "Sans Nom",
		"PDV_CONTACT_WEBSITE_*": "%s",
		"PDV_CONTACT_EMAIL_*": "%s",
		"PDV_CONTACT_FACEBOOK_*": "%s",
		"PDV_CONTACT_PHONE_*": "%s",
		"PDV_WEBSITE_*": "%s",
		"PDV_EMAIL_*": "%s",
		"PDV_FACEBOOK_*": "%s",
		"PDV_PHONE_*": "%s",
		"PDV_ADDRESS_UNKNOWN": "Addresse inconnue",
		"PDV_COMMUNE_UNKNOWN": "?",
		"PDV_STREET_UNKNOWN": "Rue inconnue",
		"PDV_HOUSENUMBER_UNKNOWN": "?",
		"PDV_ZIPCODE_UNKNOWN": "Code postal inconnu",
		"PDV_ADDRESS_LOADING": "<i class='color-red'>Chargement d'adresse</i>",
		"PDV_TITLE_HOME": "General",
		"PDV_TITLE_BABY": "Adapté aux bébés",
		"PDV_TITLE_OH": "Horaires d'ouverture",
		"PDV_TITLE_CONTACT": "Contact",
		"PDV_TITLE_MI": "Plus d'informations",
		"PDV_DIAPER_YES": "Table à langer",
		"PDV_DIAPER_NO": "No Table à langer (EN)",
		"PDV_DIAPER_*": "Table à langer",
		"PDV_DIAPER_LIMITED": "Table à langer limitée",
		"PDV_DIAPER_ROOM": "Pièce dédiée à une table à langer",
		"PDV_DIAPER_MALE_YES": "Toilettes pour homme",
		"PDV_DIAPER_FEMALE_YES": "Toilettes pour femme",
		"PDV_DIAPER_UNISEX_YES": "Toilettes unisexes",
		"PDV_DIAPER_FEE_YES": "Payant",
		"PDV_DIAPER_FEE_NO": "Gratuit",
		"PDV_CHANGINGTABLE_YES": "Table à langer",
		"PDV_CHANGINGTABLE_NO": "No Table à langer (EN)",
		"PDV_CHANGINGTABLE_LIMITED": "Table à langer limitée",
		"PDV_CHANGINGTABLE_LOCATION_ROOM": "Pièce dédiée à de multiples choses",
		"PDV_CHANGINGTABLE_LOCATION_DEDICATEDROOM": "Pièce dédiée à une table à langer",
		"PDV_CHANGINGTABLE_LOCATION_MALETOILET": "Toilettes pour homme",
		"PDV_CHANGINGTABLE_LOCATION_FEMALETOILET": "Toilettes pour femme",
		"PDV_CHANGINGTABLE_LOCATION_UNISEXTOILET": "Toilettes unisexes",
		"PDV_CHANGINGTABLE_LOCATION_WHEELCHAIRTOILET": "Toilettes pour PMR",
		"PDV_CHANGINGTABLE_LOCATION_SALESAREA": "Surface de vente",
		"PDV_CHANGINGTABLE_FEE_YES": "Payant",
		"PDV_CHANGINGTABLE_FEE_NO": "Gratuit",
		"PDV_HIGHCHAIR_YES": "Chaise haute",
		"PDV_HIGHCHAIR_*": "Chaises hautes",
		"PDV_KIDSAREA_YES": "Espace enfant",
		"PDV_KIDSAREA_NO": "No area for kids (en)",
		"PDV_KIDSAREA_INDOOR_YES": "Intérieur",
		"PDV_KIDSAREA_OUTDOOR_YES": "Extérieur",
		"PDV_KIDSAREA_SUPERVISED_YES": "Surveillé",
		"PDV_KIDSAREA_FEE_YES": "Payant",
		"PDV_STROLLER_YES": "Adapté aux poussettes",
		"PDV_STROLLER_LIMITED": "Partiellement adapté aux poussettes",
		"PDV_STROLLER_NO": "Pas adapté aux poussettes",
		"PDV_BABYFEEDING_YES": "Allaitement",
		"PDV_BABYFEEDING_NO": "Pas d'allaitement",
		"PDV_BABYFEEDING_ROOM": "Pièce",
		"PDV_BABYFEEDING_MALE_YES": "Pour homme",
		"PDV_BABYFEEDING_FEMALE_YES": "Pour femme",
		"PDV_LEISURE_PLAYGROUND": "Playground equipment",
		"PDV_LEISURE_PLAYGROUND": "Équipements d'aires de jeux",
		"PDV_MINAGE_*": "Âge mini : %s",
		"PDV_MAXAGE_*": "Âge maxi: %s",
		"PDV_PLAYGROUND_SLIDE_YES": "Toboggan",
		"PDV_PLAYGROUND_SWING_YES": "Balançoire",
		"PDV_PLAYGROUND_CLIMBINGFRAME_YES": "Équipement d'escalade",
		"PDV_PLAYGROUND_CLIMBINGWALL_YES": "Équipement d'escalade",
		"PDV_PLAYGROUND_SLEDDING_YES": "Terrain de luge",
		"PDV_PLAYGROUND_SANDPIT_YES": "Bac à sable",
		"PDV_PLAYGROUND_SEESAW_YES": "Balançoire à bascule",
		"PDV_PLAYGROUND_SPRINGY_YES": "Fauteuil à ressort",
		"PDV_PLAYGROUND_PLAYHOUSE_YES": "Petite Maisonnette",
		"PDV_PLAYGROUND_ROUNDABOUT_YES": "Tourniquet",
		"PDV_PLAYGROUND_MULTIPLAY_YES": "Multi-jeu",
		"PDV_PLAYGROUND_BASKETSWING_YES": "Panier à bascule",
		"PDV_PLAYGROUND_STRUCTURE_YES": "Structure",
		"PDV_PLAYGROUND_ZIPWIRE_YES": "Tyrolienne",
		"PDV_PLAYGROUND_BALANCEBEAM_YES": "Poutre d'équilibre",
		"PDV_PLAYGROUND_WATER_YES": "Jeux d'eau",
		"PDV_PLAYGROUND_TRAMPOLINE_YES": "Trampoline",
		"PDV_PLAYGROUND_TEENSHELTER_YES": "Abri pour enfants",
		"PDV_PLAYGROUND_CHAINLADDER_YES": "Échelle à chaîne",
		"PDV_PLAYGROUND_HOPSCOTCH_YES": "Marelle",
		"PDV_PLAYGROUND_CLIMBWALL_YES": "Mur d'escalade enfant",
		"PDV_PLAYGROUND_TUNNELTUBE_YES": "Tube de tunnel",
		"PDV_PLAYGROUND_CHESSTABLE_YES": "Table d'échecs",
		"PDV_PLAYGROUND_TREEHOUSE_YES": "Maison dans l'arbre",
		"PDV_PLAYGROUND_BASKETBALLBACKBOARDS_YES": "Panneaux de basket-ball",
		"PDV_PLAYGROUND_CUSHION_YES": "Château gonflable",
		"PDV_PLAYGROUND_SKATEEQUIPMENT_YES": "Équipement de patinage",
		"PDV_WHEELCHAIR_YES": "Accessible PMR",
		"PDV_WHEELCHAIR_NO": "Non accessible PMR",
		"PDV_MATERIAL_WOOD": "Matériau : bois",
		"PDV_MATERIAL_METAL": "Matériau : métal",
		"PDV_MATERIAL_STEEL": "Matériau : acier",
		"PDV_MATERIAL_PLASTIC": "Matériau : plastique",
		"PDV_MATERIAL_ROPE": "Matériau : cordes",
		"PDV_CAPACITY_DISABLED_YES": "Accessible aux handicapés",
		"PDV_CAPACITY_DISABLED_NO": "Not accessible aux handicapés",
		"PDV_BABY_YES": "Adapté aux bébés",
		"PDV_BABY_NO": "Not adapté aux bébés",
		"PDV_BABY_ONLY": "Uniquement pour les bébés",
		"PDV_SURFACE_SAND": "Surface : sable",
		"PDV_SURFACE_WOOD": "Surface : bois",
		"PDV_SURFACE_GRASS": "Surface : herbe",
		"PDV_SURFACE_WOODCHIPS": "Surface : copeaux de bois",
		"PDV_SURFACE_TARTAN": "Surface : tartan",
		"PDV_SURFACE_GRAVEL": "Surface : gravier",
		"PDV_SURFACE_PAVINGSTONES": "Surface : pavés",
		"PDV_SURFACE_ASPHALT": "Surface : asphalte",
		"PDV_ACCESS_YES": "Accès autorisé",
		"PDV_ACCESS_NO": "Accès interdit",
		"PDV_ACCESS_CUSTOMERS": "Réservé aux clients",
		"PDV_ACCESS_PRIVATE": "Équipement privé",
		"PDV_OPERATOR": "Opérateur",
		"PDV_DESCRIPTION": "Description",
		"TOILET": "Toilettes",
		"LNK_IMPRESS": "A propos",
		"LNK_IMPRESS_URL": "impressum.html#fr",
		"LNK_PP_SITE": "Politique de confidentialité (v.3)",
		"LNK_PP_SITE_URL": "privacypolicy-fr.html",
		"LNK_GITHUB": "Sur Github",
		"LNK_OSMWIKI": "Wiki OSM",
		"LNK_ABOUT": "About (EN)",
		"LNK_EXPLANATIONMENUBUTTONS": "Bar explained (EN)",
		"LNK_EXPLANATIONMARKERDOTS": "Traffic light system explained (EN)",
		"LNK_EXPLANATIONUSAGE": "Babykarte explained (EN)",
		"LNK_EXPLANATIONPDVICONS": "Icons explained (EN)",
		"LASTUPDATE": "Last update of map data: %s (EN)",
		"OSM_ATTRIBUTION": "Proudly collected by <a rel='noopener' target='_blank' href='http://www.openstreetmap.fr/contribuer/'>OpenStreetMap</a> (EN)",
		"TB_SEARCHFIELD": "Rechercher",
		"opening_hours": {
			"Mo": "Lundi",
			"Tu": "Mardi",
			"We": "Mercredi",
			"Th": "Jeudi",
			"Fr": "Vendredi",
			"Sa": "Samedi",
			"Su": "Dimanche",
			"off": "fermé",
			"closed": "fermé",
			"Jan": "Janvier",
			"Feb": "Février",
			"Mar": "Mars",
			"Apr": "Avril",
			"May": "Mai",
			"Jun": "Juin",
			"Jul": "Juillet",
			"Aug": "Août",
			"Sep": "Septembre",
			"Oct": "Octobre",
			"Nov": "Novembre",
			"Dec": "Décembre",
			"PH": "vacances",
			"SH": "school holidays (EN)",
			"sunrise": "sunrise (EN)",
			"sunset": "sunset (EN)",
			"dawn": "dawn (EN)",
			"dusk": "dusk (EN)"
		},
		"filtername": {
			"paediatrics": "Pédiatres / services de pédiatrie",
			"midwife": "Sages-femmes",
			"birthing_center": "Natalités",
			"playground": "Aires de jeux",
			"play-equipment": "Équipement d'aires de jeu",
			"park": "Parcs",
			"shop-babygoods": "Magasins d'articles pour bébés",
			"shop-toys": "Magasins de jouets",
			"shop-clothes": "Magasins de chaussures",
			"childcare": "Jardins d'enfants et garderies",
			"zoo": "Zoos",
			"changingtable": "Tables à langer",
			"changingtable-men": "Uniquement les tables à langer accessibles aux hommes",
			"cafe": "Cafés",
			"restaurant": "Restaurants",
			"fast_food": "Fast-Food"
		}
	},
	"site-impress": {
		"LNK_IMPRESS": "A propos",
		"LNK_IMPRESS_URL": "impressum.html#fr",
		"LNK_PP_SITE": "Politique de confidentialité (v.3)",
		"LNK_PP_SITE_URL": "privacypolicy-fr.html",
		"LNK_GITHUB": "Sur Github",
		"LNK_OSMWIKI": "Wiki OSM",
		"IMPRESS_TITLE": "A propos",
		"IMPRESS_SUBTITLE": "Responsable du site Web",
		"IMPRESS_COUNTRY": "Allemagne",
		"IMPRESS_CONTACT": "Contact",
		"IMPRESS_NOTE": "Toutes les données disponibles sur ce site proviennent d'OpenStreetMap. Babykarte n'utilise que les données. Nous ne garantissons pas l'exactitude de ces informations. Grâce aux liens fournis, vous pouvez signaler des données erronées ou manquantes à OpenStreetMap. Vous pouvez également corriger les erreurs ou ajouter d'autres informations par vous-même."
	}
};
refFr["site-map"].filtertranslations = {
	"healthcare=doctor": ["Pédiatre", "paediatrics"],
	"healthcare=hospital": ["Hôpital", ""],
	"healthcare=midwife": ["Sage-femme", "midwife"],
	"healthcare=birthing_center": ["Natalité", "birthing_center"],
	"amenity=toilets": ["Toilettes", ""],
	"amenity=cafe": ["Café", "cafe"],
	"amenity=restaurant": ["Restaurant", "restaurant"],
	"amenity=fast_food": ["Restauration rapide", "fast_food"],
	"amenity=kindergarten": ["Jardin d'enfants", ""],
	"amenity=childcare": ["Garderie", "childcare"],
	"leisure=playground": ["Aire de jeu", "playground"],
	"leisure=park": ["Parc", "park"],
	"tourism=zoo": ["Zoo", "zoo"],
	"shop=baby_goods": ["Articles pour bébé", "shop-babygoods"],
	"shop=toys": ["Magasin de jouets", "shop-toys"],
	"shop=clothes": ["Vêtements", "shop-clothes"],
	"shop=chemist": ["Pharmacie", ""],
	"shop=supermarket": ["Supermarché", ""]
};
refEn["site-map"].categories {
	"health": [["Health"], ["Hospital", "doctor", "paediatrics", "dentist"]],
	"activity": [["Activity"], ["Zoo", "Playground", "Park"]],
	"childcare": [["Childcare"], ["Kindergarten", "Childcare", "Nappy", "Diaper", "Changing table"]],
	"shop": [["Shop"], ["Goods", "Clothes", "Toys"]],
	"eat": [["Food&Drink"], ["Food", "Drink", "Cafe", "Restaurant"]]
};
registerLang("fr", refFr);
setLang("", "fr");
