var refFr = {"site-map": {
	"LOCATING_FAILURE": "N'a pas trouvé votre lieu",
	"LOCATING_SUCCESS": "Votre lieu",
	"LOADING_FAILURE": "Une erreur s'est produite, veuillez zoomer et réessayer",
	"NODATA": "No '<i>%s</i>' found here! (EN)",
	"ERROR404": "Backend does not support filter '<i>%s</i>' (EN)",
	"ERROR503": "Error in requesting database for filter '<i>%s</i>' (EN)",
	"ERROR": "An unknown error interrupts the party (EN)",
	"LNK_OSM_EDIT": "Modifier dans OSM",
	"LNK_OSM_REPORT": "Signaler une information erronée",
	"LNK_OSM_VIEW": "Voir le Point d'intérêt dans OpenStreetMap",
	"LNK_OPEN_WITH": "Ouvrir avec une appli",
	"FLTR_NOTHINGSELECTED": "Please touch the <img class='bar-icon' src='images/checkmark.svg' /> icon in the menu to select filters. (EN)",
	"FLTR_SELECTALL": "(De)sélectionnez tout",
	"PDV_UNNAME": "Sans Nom",
	"PDV_CONTACT_WEBSITE_*": "%s",
	"PDV_CONTACT_EMAIL_*": "%s",
	"PDV_CONTACT_FACEBOOK_*": "%s",
	"PDV_CONTACT_PHONE_*": "%s",
	"PDV_WEBSITE_*": "%s",
	"PDV_EMAIL_*": "%s",
	"PDV_FACEBOOK_*": "%s",
	"PDV_PHONE_*": "%s",
	"PDV_ADDRESS_UNKNOWN": "Addresse inconnue",
	"PDV_COMMUNE_UNKNOWN": "?",
	"PDV_STREET_UNKNOWN": "Rue inconnue",
	"PDV_HOUSENUMBER_UNKNOWN": "?",
	"PDV_ZIPCODE_UNKNOWN": "Code postal inconnu",
	"PDV_ADDRESS_LOADING": "<i class='color-red'>Address loading</i> (EN)",
	"PDV_TITLE_HOME": "General",
	"PDV_TITLE_BABY": "Adapté aux bébés",
	"PDV_TITLE_OH": "Horaires d'ouverture",
	"PDV_TITLE_CONTACT": "Contact",
	"PDV_TITLE_MI": "Plus d'informations",
	/*"PDV_DIAPER_YES": "Table à langer disponible",
	"PDV_DIAPER_NO": "Pas de table à langer disponible",
	"PDV_DIAPER_LIMITED": "Possibilité de changement limitée",
	"PDV_DIAPER_ROOM": "Vestiaire à langer",
	"PDV_DIAPER_MALE_YES": "dans les toilettes pour hommes",
	"PDV_DIAPER_FEMALE_YES": "dans les toilettes pour femmes",
	"PDV_DIAPER_UNISEX_YES": "dans les toilettes unisexes",
	"PDV_DIAPER_FEE_YES": "Payant",
	"PDV_DIAPER_FEE_NO": "Gratuit",
	"PDV_DIAPER_UNKNOWN": "Existence d'une table à langer inconnue",*/
	/*"PDV_DIAPER_YES": "Changing table available",
	"PDV_DIAPER_NO": "No changing table available",
	"PDV_DIAPER_LIMITED": "Limited changing facilities available.",
	"PDV_DIAPER_ROOM": "Diaper-changing room",
	"PDV_DIAPER_MALE_YES": "in the men's room",
	"PDV_DIAPER_FEMALE_YES": "in the ladies' room",
	"PDV_DIAPER_UNISEX_YES": "in the unisex toilet",
	"PDV_DIAPER_FEE_YES": "Fee applies",
	"PDV_DIAPER_FEE_NO": "No fee applies",
	"PDV_DIAPER_UNKNOWN": "Existence of changing table unknown",*/
	"PDV_DIAPER_YES": "Changing table (EN)",
	"PDV_DIAPER_LIMITED": "Limited changing facilities (EN)",
	"PDV_DIAPER_ROOM": "Diaper-changing room (EN)",
	"PDV_DIAPER_MALE_YES": "male toilet (EN)",
	"PDV_DIAPER_FEMALE_YES": "female toilet (EN)",
	"PDV_DIAPER_UNISEX_YES": "unisex toilet (EN)",
	"PDV_DIAPER_FEE_YES": "Fee applies (EN)",
	"PDV_DIAPER_FEE_NO": "No fees (EN)",
	/*"PDV_CHANGINGTABLE_YES": "Table à langer disponible",
	"PDV_CHANGINGTABLE_NO": "Pas de table à langer disponible",
	"PDV_CHANGINGTABLE_LIMITED": "Possibilité de changement limitée",
	"PDV_CHANGINGTABLE_LOCATION_ROOM": "Dans une salle polyvalente",
	"PDV_CHANGINGTABLE_LOCATION_DEDICATEDROOM": "dans une salle dédiée",
	"PDV_CHANGINGTABLE_LOCATION_MALETOILET": "dans les toilettes pour hommes",
	"PDV_CHANGINGTABLE_LOCATION_FEMALETOILET": "dans les toilettes pour femmes",
	"PDV_CHANGINGTABLE_LOCATION_UNISEXTOILET": "dans les toilettes unisexes",
	"PDV_CHANGINGTABLE_LOCATION_WHEELCHAIRTOILET": "dans les toilettes pour handicapés",
	"PDV_CHANGINGTABLE_LOCATION_SALESAREA": "directement dans la zone commerciale",
	"PDV_CHANGINGTABLE_FEE_YES": "Payant",
	"PDV_CHANGINGTABLE_FEE_NO": "Gratuit",
	"PDV_CHANGINGTABLE_UNKNOWN": "Existence d'une table à langer inconnue",*/
	/*"PDV_CHANGINGTABLE_YES": "Changing table available",
	"PDV_CHANGINGTABLE_NO": "No changing table available",
	"PDV_CHANGINGTABLE_LIMITED": "Limited changing facilities available.",
	"PDV_CHANGINGTABLE_LOCATION_ROOM": "In a multi-purpose room",
	"PDV_CHANGINGTABLE_LOCATION_DEDICATEDROOM": "in a diaper-changing room",
	"PDV_CHANGINGTABLE_LOCATION_MALETOILET": "in the men's room",
	"PDV_CHANGINGTABLE_LOCATION_FEMALETOILET": "in the ladies' room",
	"PDV_CHANGINGTABLE_LOCATION_UNISEXTOILET": "in the unisex toilet",
	"PDV_CHANGINGTABLE_LOCATION_WHEELCHAIRTOILET": "in the wheelchair users' room",
	"PDV_CHANGINGTABLE_LOCATION_SALESAREA": "right in the sales area",
	"PDV_CHANGINGTABLE_FEE_YES": "Fee applies",
	"PDV_CHANGINGTABLE_FEE_NO": "No fee applies",
	"PDV_CHANGINGTABLE_UNKNOWN": "Existence of changing table unknown",*/
	"PDV_CHANGINGTABLE_YES": "Changing table (EN)",
	"PDV_CHANGINGTABLE_LIMITED": "Limited changing facilities (EN)",
	"PDV_CHANGINGTABLE_LOCATION_ROOM": "Multi-purpose room (EN)",
	"PDV_CHANGINGTABLE_LOCATION_DEDICATEDROOM": "Diaper-changing room (EN)",
	"PDV_CHANGINGTABLE_LOCATION_MALETOILET": "Male toilet (EN)",
	"PDV_CHANGINGTABLE_LOCATION_FEMALETOILET": "Female toilet (EN)",
	"PDV_CHANGINGTABLE_LOCATION_UNISEXTOILET": "Unisex toilet (EN)",
	"PDV_CHANGINGTABLE_LOCATION_WHEELCHAIRTOILET": "Wheelchair users' toilet (EN)",
	"PDV_CHANGINGTABLE_LOCATION_SALESAREA": "Sales area (EN)",
	"PDV_CHANGINGTABLE_FEE_YES": "Fee applies (EN)",
	"PDV_CHANGINGTABLE_FEE_NO": "No fees (EN)",
	/*"PDV_HIGHCHAIR_YES": "Chaise haute disponible",
	"PDV_HIGHCHAIR_NO": "Chaise haute non disponible",
	"PDV_HIGHCHAIR_COUNT": "chaises hautes disponibles",
	"PDV_HIGHCHAIR_UNKNOWN": "Existence de chaises hautes inconnue",*/
	/*"PDV_HIGHCHAIR_YES": "Highchair available",
	"PDV_HIGHCHAIR_NO": "Highchair not available",
	"PDV_HIGHCHAIR_COUNT": "highchairs available",
	"PDV_HIGHCHAIR_UNKNOWN": "Existence of highchairs unknown",*/
	"PDV_HIGHCHAIR_YES": "Highchair (EN)",
	"PDV_HIGHCHAIR_COUNT": "highchairs (EN)",
	/*"PDV_KIDSAREA_YES": "Espace enfants disponible",
	"PDV_KIDSAREA_NO": "Espace enfants non disponible",
	"PDV_KIDSAREA_INDOOR_YES": "Espace enfants intérieur",
	"PDV_KIDSAREA_OUTDOOR_YES": "Espace enfants extérieur",
	"PDV_KIDSAREA_SUPERVISED_YES": "Espace enfants surveillé",
	"PDV_KIDSAREA_FEE_YES": "Payant",
	"PDV_KIDSAREA_UNKNOWN": "Existence d'espaces enfants inconnue",*/
	/*"PDV_KIDSAREA_YES": "Kids area available",
	"PDV_KIDSAREA_NO": "Kids area not available",
	"PDV_KIDSAREA_INDOOR_YES": "Kids area is inside",
	"PDV_KIDSAREA_OUTDOOR_YES": "Kids area is outside",
	"PDV_KIDSAREA_SUPERVISED_YES": "Kids area is supervised",
	"PDV_KIDSAREA_FEE_YES": "Fee must be paid",
	"PDV_KIDSAREA_UNKNOWN": "Existence of a kids' area unknown",*/
	"PDV_KIDSAREA_YES": "Kids area (EN)",
	"PDV_KIDSAREA_INDOOR_YES": "Inside (EN)",
	"PDV_KIDSAREA_OUTDOOR_YES": "Outside (EN)",
	"PDV_KIDSAREA_SUPERVISED_YES": "Supervised (EN)",
	"PDV_KIDSAREA_FEE_YES": "Fee applies (EN)",
	/*"PDV_STROLLER_YES": "Le lieu est adapté aux poussettes",
	"PDV_STROLLER_LIMITED": "Le lieu est partiellement adapté aux poussettes",
	"PDV_STROLLER_NO": "Le lieu n'est pas adapté aux poussettes",
	"PDV_STROLLER_UNKNOWN": "Support aux poussettes inconnu",*/
	/*"PDV_STROLLER_YES": "Location is stroller friendly",
	"PDV_STROLLER_LIMITED": "Location is partially stroller friendly",
	"PDV_STROLLER_NO": "Location isn't stroller friendly",
	"PDV_STROLLER_UNKNOWN": "Stroller friendliness unknown",*/
	"PDV_STROLLER_YES": "Stroller friendly (EN)",
	"PDV_STROLLER_LIMITED": "Partially stroller friendly (EN)",
	"PDV_STROLLER_NO": "Not stroller friendly (EN)",
	/*"PDV_BABYFEEDING_YES": "Lieu pour l'allaitement (au sein) disponible",
	"PDV_BABYFEEDING_NO": "Pas de lieu pour l'allaitement (au sein) disponible",
	"PDV_BABYFEEDING_ROOM": "Salle pour l'allaitement (au sein) disponible",
	"PDV_BABYFEEDING_MALE_YES": "Lieu pour les hommes pour nourrir un bébé disponible",
	"PDV_BABYFEEDING_FEMALE_YES": "Lieu pour les femmes pour nourrir un bébé disponible",
	"PDV_BABYFEEDING_MALE_NO": "Pas de lieu pour les hommes pour nourrir un bébé disponible",
	"PDV_BABYFEEDING_FEMALE_NO": "Pas de lieu pour les femmes pour nourrir un bébé disponible",*/
	/*"PDV_BABYFEEDING_YES": "Place for (breast-)feeding available",
	"PDV_BABYFEEDING_NO": "No place for (breast-)feeding available",
	"PDV_BABYFEEDING_ROOM": "Room for (breast-)feeding available",
	"PDV_BABYFEEDING_MALE_YES": "Place for men to feed a baby available",
	"PDV_BABYFEEDING_FEMALE_YES": "Place for women to feed a baby available",
	"PDV_BABYFEEDING_MALE_NO": "No place for men to feed a baby available",
	"PDV_BABYFEEDING_FEMALE_NO": "No place for women to feed a baby available",*/
	"PDV_BABYFEEDING_YES": "(Breast-)feeding (EN)",
	"PDV_BABYFEEDING_NO": "No (breast-)feeding (EN)",
	"PDV_BABYFEEDING_ROOM": "Room (EN)",
	"PDV_BABYFEEDING_MALE_YES": "for men (EN)",
	"PDV_BABYFEEDING_FEMALE_YES": "For women (EN)",
	"PDV_LEISURE_PLAYGROUND": "Playground equipment",
	"PDV_LEISURE_PLAYGROUND": "Équipements d'aires de jeux",
	"PDV_MINAGE_*": "Âge mini : %s",
	"PDV_MAXAGE_*": "Âge maxi: %s",
	"PDV_PLAYGROUND_SLIDE_YES": "Toboggan",
	"PDV_PLAYGROUND_SWING_YES": "Balançoire",
	"PDV_PLAYGROUND_CLIMBINGFRAME_YES": "Équipement d'escalade",
	"PDV_PLAYGROUND_CLIMBINGWALL_YES": "Équipement d'escalade",
	"PDV_PLAYGROUND_SLEDDING_YES": "Terrain de luge",
	"PDV_PLAYGROUND_SANDPIT_YES": "Bac à sable",
	"PDV_PLAYGROUND_SEESAW_YES": "Balançoire à bascule",
	"PDV_PLAYGROUND_SPRINGY_YES": "Fauteuil à ressort",
	"PDV_PLAYGROUND_PLAYHOUSE_YES": "Petite Maisonnette",
	"PDV_PLAYGROUND_ROUNDABOUT_YES": "Tourniquet",
	"PDV_PLAYGROUND_MULTIPLAY_YES": "Multi-jeu",
	"PDV_PLAYGROUND_BASKETSWING_YES": "Panier à bascule",
	"PDV_PLAYGROUND_STRUCTURE_YES": "Structure",
	"PDV_PLAYGROUND_ZIPWIRE_YES": "Tyrolienne",
	"PDV_PLAYGROUND_BALANCEBEAM_YES": "Poutre d'équilibre",
	"PDV_PLAYGROUND_WATER_YES": "Jeux d'eau",
	"PDV_PLAYGROUND_TRAMPOLINE_YES": "Trampoline",
	"PDV_PLAYGROUND_TEENSHELTER_YES": "Abri pour enfants",
	"PDV_PLAYGROUND_CHAINLADDER_YES": "Échelle à chaîne",
	"PDV_PLAYGROUND_HOPSCOTCH_YES": "Marelle",
	"PDV_PLAYGROUND_CLIMBWALL_YES": "Mur d'escalade enfant",
	"PDV_PLAYGROUND_TUNNELTUBE_YES": "Tube de tunnel",
	"PDV_PLAYGROUND_CHESSTABLE_YES": "Table d'échecs",
	"PDV_PLAYGROUND_TREEHOUSE_YES": "Maison dans l'arbre",
	"PDV_PLAYGROUND_BASKETBALLBACKBOARDS_YES": "Panneaux de basket-ball",
	"PDV_PLAYGROUND_CUSHION_YES": "Château gonflable",
	"PDV_PLAYGROUND_SKATEEQUIPMENT_YES": "Équipement de patinage",
	"PDV_WHEELCHAIR_YES": "Accessible PMR",
	"PDV_WHEELCHAIR_NO": "Non accessible PMR",
	"PDV_MATERIAL_WOOD": "Matériau : bois",
	"PDV_MATERIAL_METAL": "Matériau : métal",
	"PDV_MATERIAL_STEEL": "Matériau : acier",
	"PDV_MATERIAL_PLASTIC": "Matériau : plastique",
	"PDV_MATERIAL_ROPE": "Matériau : cordes",
	"PDV_CAPACITY_DISABLED_YES": "Accessible aux handicapés",
	"PDV_CAPACITY_DISABLED_NO": "Not accessible aux handicapés",
	"PDV_BABY_YES": "Adapté aux bébés",
	"PDV_BABY_NO": "Not adapté aux bébés",
	"PDV_BABY_ONLY": "Uniquement pour les bébés",
	"PDV_SURFACE_SAND": "Surface : sable",
	"PDV_SURFACE_WOOD": "Surface : bois",
	"PDV_SURFACE_GRASS": "Surface : herbe",
	"PDV_SURFACE_WOODCHIPS": "Surface : copeaux de bois",
	"PDV_SURFACE_TARTAN": "Surface : tartan",
	"PDV_SURFACE_GRAVEL": "Surface : gravier",
	"PDV_SURFACE_PAVINGSTONES": "Surface : pavés",
	"PDV_SURFACE_ASPHALT": "Surface : asphalte",
	"PDV_ACCESS_YES": "Accès autorisé",
	"PDV_ACCESS_NO": "Accès interdit",
	"PDV_ACCESS_CUSTOMERS": "Réservé aux clients",
	"PDV_ACCESS_PRIVATE": "Équipement privé",
	"PDV_OPERATOR": "Opérateur",
	"PDV_DESCRIPTION": "Description",
	"TOILET": "Toilettes",
	"LNK_IMPRESS": "A propos",
	"LNK_IMPRESS_URL": "impressum.html#fr",
	"LNK_PP_SITE": "Politique de confidentialité (v.2)",
	"LNK_PP_SITE_URL": "privacypolicy-fr.html",
	"LNK_GITHUB": "Sur Github",
	"LNK_OSMWIKI": "Wiki OSM",
	"TB_SEARCHFIELD": "Rechercher",
	"opening_hours": {"Mo" : "Lundi", "Tu" : "Mardi", "We" : "Mercredi", "Th" : "Jeudi", "Fr" : "Vendredi", "Sa" : "Samedi", "Su" : "Dimanche", "off" : "fermé", "Jan" : "Janvier", "Feb" : "Février", "Mar" : "Mars", "Apr" : "Avril", "May" : "Mai", "Jun" : "Juin", "Jul" : "Juillet", "Aug" : "Août", "Sep" : "Septembre", "Oct" : "Octobre", "Nov" : "Novembre", "Dec" : "Décembre", "PH" : "vacances"},
	"filtername": {
		"paediatrics": "Pédiatres / services de pédiatrie",
		"midwife": "Sages-femmes",
		"birthing_center": "Natalités",
		"playground": "Aires de jeux",
		"play-equipment": "Équipement d'aires de jeu",
		"park": "Parcs",
		"shop-babygoods": "Magasins d'articles pour bébés",
		"shop-toys": "Magasins de jouets",
		"shop-clothes": "Magasins de chaussures",
		"childcare": "Jardins d'enfants et garderies",
		"zoo": "Zoos",
		"changingtable": "Tables à langer",
		"changingtable-men": "Uniquement les tables à langer accessibles aux hommes",
		"cafe": "Cafés",
		"restaurant": "Restaurants",
		"fast_food": "Fast-Food"
	}
},
"site-impress" : {
	"IMPRESS_TITLE": "A propos",
	"IMPRESS_SUBTITLE": "Responsable du site Web",
	"IMPRESS_COUNTRY": "Allemagne",
	"IMPRESS_CONTACT": "Contact",
	"IMPRESS_NOTE": "Toutes les données disponibles sur ce site proviennent d'OpenStreetMap. Babykarte n'utilise que les données. Nous ne garantissons pas l'exactitude de ces informations. Grâce aux liens fournis, vous pouvez signaler des données erronées ou manquantes à OpenStreetMap. Vous pouvez également corriger les erreurs ou ajouter d'autres informations par vous-même."
	}
};
refFr["site-map"].filtertranslations = {
	"healthcare=doctor": "Pédiatre",
	"healthcare=hospital": "Hôpital",
	"healthcare=midwife": "Sage-femme",
	"healthcare=birthing_center": "Natalité",
	"amenity=toilets": "Toilettes",
	"amenity=cafe": "Café",
	"amenity=restaurant": "Restaurant",
	"amenity=fast_food" :"Restauration rapide",
	"amenity=kindergarten" : "Jardin d'enfants",
	"amenity=childcare" : "Garderie",
	"leisure=playground": "Aire de jeu",
	"leisure=park": "Parc",
	"tourism=zoo": "Zoo",
	"shop=baby_goods": "Articles pour bébé",
	"shop=toys": "Magasin de jouets",
	"shop=clothes": "Vêtements",
	"shop=chemist": "Pharmacie",
	"shop=supermarket": "Supermarché"
}
registerLang("fr", refFr);
setLang("", "fr");
